---
- name: Setup Jenkins and Docker
  hosts: vm2
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name:
          - openjdk-11-jdk
          - docker.io
        state: present
        update_cache: yes

    - name: Tambahkan repository Jenkins
      shell: |
        wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
        apt update

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Start dan enable Jenkins & Docker
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - jenkins
        - docker

    - name: Tambahkan user Jenkins ke grup Docker
      user:
        name: jenkins
        groups: docker
        append: yes
