- name: Install and Configure Grafana
  hosts: grafana
  become: yes
  tasks:
  
    - name: Add Grafana APT Key
      apt_key:
        url: https://packages.grafana.com/gpg.key
        state: present

    - name: Add Grafana APT Repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
        filename: grafana

    - name: Install Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Ensure Grafana service is enabled and started
      service:
        name: grafana-server
        enabled: yes
        state: started

    - name: Copy Data Source Config
      copy:
        src: files/prometheus.yml
        dest: /etc/grafana/provisioning/datasources/prometheus.yml

    - name: Copy Dashboard Config
      copy:
        src: files/dashboard.yml
        dest: /etc/grafana/provisioning/dashboards/dashboard.yml

    - name: Ensure Dashboard Directory Exists
      file:
        path: /etc/grafana/dashboards
        state: directory
        mode: "0755"

    - name: Copy Dashboard JSON
      copy:
        src: files/node-exporter.json
        dest: /etc/grafana/dashboards/node-exporter.json

    - name: Restart Grafana
      service:
        name: grafana-server
        state: restarted
