---
- name: Setup Grafana and Prometheus
  hosts: vm3
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name:
          - prometheus
          - grafana
        state: present
        update_cache: yes

    - name: Copy konfigurasi Prometheus
      copy:
        dest: /etc/prometheus/prometheus.yml
        content: |
          global:
            scrape_interval: 15s
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
                - targets: ['localhost:9090']
            - job_name: 'jenkins'
              static_configs:
                - targets: ['IP_VM2:8080']
            - job_name: 'wordpress'
              static_configs:
                - targets: ['IP_VM1']
            - job_name: 'nextcloud'
              static_configs:
                - targets: ['IP_VM4']
      notify: Restart Prometheus

    - name: Tambahkan Prometheus sebagai data source di Grafana
      shell: |
        curl -X POST "http://admin:admin@localhost:3000/api/datasources" \
        -H "Content-Type: application/json" \
        --data-binary '{
          "name": "Prometheus",
          "type": "prometheus",
          "access": "proxy",
          "url": "http://localhost:9090",
          "isDefault": true
        }'

  handlers:
    - name: Restart Prometheus
      systemd:
        name: prometheus
        state: restarted
