- name: Install and Setup OwnCloud
  hosts: localhost
  become: yes
  tasks:

    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - php-xml
          - php-mbstring
          - php-curl
          - php-zip
          - php-gd
          - curl
          - unzip
        state: present

    - name: Start and enable Apache service
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Start and enable MySQL service
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Create MySQL Database and User for OwnCloud
      mysql_db:
        name: owncloud
        state: present

    - name: Create MySQL User
      mysql_user:
        name: ownclouduser
        password: your_password_here
        priv: "owncloud.*:ALL"
        state: present

    - name: Download OwnCloud
      get_url:
        url: https://download.owncloud.org/community/owncloud-complete-latest.zip
        dest: /tmp/owncloud.zip

    - name: Unzip OwnCloud
      unarchive:
        src: /tmp/owncloud.zip
        dest: /var/www/html/
        remote_src: yes

    - name: Set permissions for OwnCloud
      file:
        path: /var/www/html/owncloud
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Configure Apache for OwnCloud
      copy:
        dest: /etc/apache2/sites-available/owncloud.conf
        content: |
          Alias /owncloud "/var/www/html/owncloud/"
          <Directory /var/www/html/owncloud/>
              Options +FollowSymlinks
              AllowOverride All
              Require all granted
          </Directory>
          <Directory /var/www/html/owncloud/data/>
              Require all denied
          </Directory>
          <IfModule mod_dav.c>
              Dav off
          </IfModule>
          SetEnv HOME /var/www/html/owncloud
          SetEnv HTTP_HOME /var/www/html/owncloud
        owner: root
        group: root
        mode: '0644'

    - name: Enable Apache mod_rewrite
      command: a2enmod rewrite

    - name: Enable OwnCloud site
      command: a2ensite owncloud

    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted

    - name: Clean up downloaded zip file
      file:
        path: /tmp/owncloud.zip
        state: absent
