---
- name: Setup WordPress, MySQL, Apache2 (Localhost)
  hosts: localhost
  become: yes

  vars:
    db_name: wordpress
    db_user: wpuser
    db_password: kyput
    wp_install_dir: /var/www/html

  tasks:
    - name: Install dependencies
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - php-soap
          - php-intl
          - php-zip
          - unzip
          - curl
        state: present
        update_cache: yes

    - name: Start and enable Apache2 & MySQL
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - mysql

    - name: Secure MySQL - Set root password and change auth method
      mysql_user:
        name: root
        password: kyput
        login_unix_socket: /var/run/mysqld/mysqld.sock
        priv: "*.*:ALL,GRANT"
        host: localhost
        state: present

    - name: Create WordPress Database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: kyput

    - name: Create MySQL User for WordPress
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        host: localhost
        state: present
        login_user: root
        login_password: kyput

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Copy WordPress to web root
      copy:
        src: "/tmp/wordpress/"
        dest: "{{ wp_install_dir }}"
        remote_src: yes
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Set ownership for WordPress files
      file:
        path: "{{ wp_install_dir }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data

    - name: Copy WordPress Config File
      template:
        src: templates/wp-config.php.j2
        dest: "{{ wp_install_dir }}/wp-config.php"
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Remove default Apache index.html
      file:
        path: "{{ wp_install_dir }}/index.html"
        state: absent

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
