---
- name: Install and Configure Nextcloud on localhost
  hosts: localhost
  become: yes
  vars:
    nextcloud_version: "26.0.0"
    mysql_root_password: "1234"  # Ubah sesuai kebutuhan
    nextcloud_db_password: "kyput"

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - php-xml
          - php-mbstring
          - php-curl
          - php-zip
          - php-gd
          - curl
          - unzip
          - python3-pip  # Pastikan pip terinstal
        state: present

    - name: Install PyMySQL
      pip:
        name: PyMySQL
        state: present

    - name: Start and enable Apache
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Start and enable MySQL
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Set MySQL root password and configure authentication
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host: localhost
        login_user: root
        login_password: ""
        state: present
        # Menggunakan mysql_native_password
        plugin: mysql_native_password

    - name: Create MySQL database for Nextcloud
      mysql_db:
        name: nextcloud
        state: present

    - name: Create MySQL user for Nextcloud
      mysql_user:
        name: nextclouduser
        password: "{{ nextcloud_db_password }}"
        host: localhost
        priv: "nextcloud.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Download Nextcloud
      get_url:
        url: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.zip"
        dest: /tmp/nextcloud.zip

    - name: Unzip Nextcloud
      unarchive:
        src: /tmp/nextcloud.zip
        dest: /var/www/html/
        remote_src: yes

    - name: Set permissions for Nextcloud directory
      file:
        path: /var/www/html/nextcloud
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Configure Apache for Nextcloud
      copy:
        content: |
          Alias /nextcloud "/var/www/html/nextcloud/"
          <Directory /var/www/html/nextcloud/>
              Options +FollowSymlinks
              AllowOverride All
              Require all granted
          </Directory>
          <Directory /var/www/html/nextcloud/data/>
              Require all denied
          </Directory>
          <IfModule mod_dav.c>
              Dav off
          </IfModule>
          SetEnv HOME /var/www/html/nextcloud
          SetEnv HTTP_HOME /var/www/html/nextcloud
        dest: /etc/apache2/sites-available/nextcloud.conf

    - name: Enable Apache site configuration
      command: a2ensite nextcloud

    - name: Enable mod_rewrite
      command: a2enmod rewrite

    - name: Restart Apache
      systemd:
        name: apache2
        state: restarted

    - name: Remove downloaded zip file
      file:
        path: /tmp/nextcloud.zip
        state: absent

    - name: Inform user
      debug:
        msg: "Nextcloud installation completed. Access it at http://localhost/nextcloud"
