---
- name: Setup Nextcloud, MySQL, Apache2 (Localhost)
  hosts: localhost
  become: yes

  vars:
    db_name: nextcloud
    db_user: ncuser
    db_password: ncpassword
    db_host: localhost
    nc_install_dir: /var/www/html/nextcloud

  tasks:
    - name: Install dependencies
      apt:
        name:
          - apache2
          - mysql-server
          - php
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - php-soap
          - php-intl
          - php-zip
          - libapache2-mod-php
          - unzip
          - curl
        state: present
        update_cache: yes

    - name: Start and enable Apache2 & MySQL
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - apache2
        - mysql

    - name: Secure MySQL - Set root password and change auth method
      mysql_user:
        name: root
        password: ncpassword
        login_unix_socket: /var/run/mysqld/mysqld.sock
        priv: "*.*:ALL,GRANT"
        host: localhost
        state: present

    - name: Create Nextcloud Database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: ncpassword

    - name: Create MySQL User for Nextcloud
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        host: localhost
        state: present
        login_user: root
        login_password: ncpassword

    - name: Download Nextcloud
      get_url:
        url: https://download.nextcloud.com/server/releases/nextcloud-25.0.0.zip
        dest: /tmp/nextcloud.zip

    - name: Extract Nextcloud
      unarchive:
        src: /tmp/nextcloud.zip
        dest: /tmp
        remote_src: yes

    - name: Copy Nextcloud to web root
      copy:
        src: "/tmp/nextcloud/"
        dest: "{{ nc_install_dir }}"
        remote_src: yes
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Set ownership for Nextcloud files
      file:
        path: "{{ nc_install_dir }}"
        state: directory
        recurse: yes
        owner: www-data
        group: www-data

    - name: Copy Nextcloud Config File
      template:
        src: templates/config.php.j2
        dest: "{{ nc_install_dir }}/config/config.php"
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Remove default Apache index.html
      file:
        path: "{{ nc_install_dir }}/index.html"
        state: absent

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
